[package]
name = "postfix-reinject"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = { version = "0.11", features = ["smtp-transport", "builder"] }
mailparse = "0.14"
regex = "1"
clap = { version = "4.0", features = ["derive"] }
